//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFClasses
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model1Container : DbContext
    {
        public Model1Container()
            : base("name=Model1Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<JH_Categorys> JH_CategorysSet1 { get; set; }
        public virtual DbSet<JH_Goods> JH_GoodsSet1 { get; set; }
        public virtual DbSet<JH_Reviews> JH_ReviewsSet { get; set; }
        public virtual DbSet<JH_Detail> JH_DetailSet { get; set; }
        public virtual DbSet<JH_BackGroundUser> JH_BackGroundUserSet { get; set; }
        public virtual DbSet<JH_UserInfo> JH_UserInfoSet { get; set; }
    }
}
